# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('time', models.DateTimeField(verbose_name='sniffed time')),
            ],
        ),
    ]
